### ISSUE TITLE
Expand strategies.py dict

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/axelrod-fortran#15]
Rather than just mapping fortran function names to axelrod-python class names, we should map to a dictionary.

That would allow us to expand the information we hold about each function without having to create new structures.

e.g.
```
strategies = {
   'ktitfortatc': {'axelrod-python class': 'TitForTat', 'stochastic': False, 'author': 'Unknown'}
}
```

**Comment by drvinceknight** [comment]
Yeah. Nice :+1: Perhaps `rank-in-original` as well which would quickly allow for a comparative analysis.

Close #14?

**Comment by meatballs** [comment]
Yep. The idea is that we can add as many additional keys as we like as we go along.

**Comment by meatballs** [comment]
there is probably a better name for the dict so that its namespace is:

`axelrod-fortran.strategies.something_meaningful`
