### ISSUE TITLE
Stochastic Classification

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/axelrod-fortran#19]
Add entries to the classifiers dict for whether a strategy is stochastic or not.

If the code makes use of the 'R' argument, it's stochastic. If not, it isn't.

Hint: A good fortran linter will flag any parameters in a function signature that aren't used within the function itself.

**Comment by drvinceknight** [comment]
If in **any** doubt on a given strategy we should classify it as `stochastic=True` (important as otherwise results will be obtained from the cache).

**Comment by meatballs** [comment]
That's what 'None' is intended to show.
i.e. it only gets set to True or False if we are certain. If not, we leave it as None.
The Player class deals with None properly

**Comment by drvinceknight** [comment]
Great :+1: Just wanted to emphasise that False Negative was better than a False positive in this case :)

**Comment by marcharper** [comment]
Hypothesis was useful for the Axelrod library to test the deterministic assertion. We should add a similar test here that will catch any such error over time.

**Comment by drvinceknight** [comment]
Great idea. I'm happy to write that once #22 is in?
