### ISSUE TITLE
Research / Paper Ideas

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/axelrod-fortran#23]
* Rerun tournament 10000x
* Rerun, adding exactly one strategy from the Axelrod library, for each strategy
* Run with all strategies from both libraries
* Run with all strategies from SP tournament

**Comment by drvinceknight** [comment]
I was thinking:

# Title: Reviving, reproducing and revisiting the Axelrod tournamentt

## Literature review/background

## Reviving the tournament

Discuss the Fortran/Python voodoo (discuss bug we found etc).

## Reproduce

Reproduce the original tournament (10000x) and carefully examine how this compares to the 1980 paper. I have two high school students working with me for 4 weeks. This would be a fun project for them.

## Revisit

Along the lines of:

> Rerun, adding exactly one strategy from the Axelrod library, for each strategy
> Run with all strategies from both libraries
> Run with all strategies from SP tournament

My thoughts were (perhaps as well as your thoughts there?):

- Run with best strategy in library
- Run with best ZD strategy/mem1 strategy in library
- Train strategies specifically for it and run

### Conclude

Hooray!

**Comment by marcharper** [comment]
I doubt we'll have to train anything but we'll see.

**Comment by meatballs** [comment]
How about trying to reproduce whatever that table coming out of TourExec means?

**Comment by drvinceknight** [comment]
Yeah that's what I meant by my "Reproduce" section: those high school students will hopefully be able to help with that too.

**Comment by drvinceknight** [comment]
Just making a note:

Axelrod's second tournament was *like* a prob end with `prob_end=.00346`. The difference being that this probability was sampled **5** times and the match lengths used were 63, 77, 151 and 308 and all matches between pairs were from those 5 values. **I know that I said 5 times but I'm only giving 4 values** ( :cry: that's just what's in the paper), thankfully the paper also reports an average length of 151 which implies a fifth value of 157.

```
>>> (63 + 77 + 151 + 308 + 157) / 5
151.0
```
We can do both this exact match length in our runs but also do a "real" prob end tournament with the given probability.

If anyone wanted to check that I'm understanding the paper correctly, this is all in "The Form of The Tournament" section of the second paper.

**Comment by drvinceknight** [comment]
Just thought I'd post the line:

> The resulting random sample from the implied distribution specified that the five games for each pair of players would be of lengths 63, 77, 151, and 308 moves. 

Seriously? Sigh... :laughing: :sob: :sob:

**Comment by drvinceknight** [comment]
Closing this, discussion can continue on: https://github.com/Axelrod-Python/revisiting-axelrod-second
