### ISSUE TITLE
Fortran question: why does k61r not behave as expected?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-fortran#60]
Similar to #59, another strategy that does not behave as expected is `k61r` which is supposed to be Champion. Here's the source code <https://github.com/Axelrod-Python/TourExec/blob/master/src/strategies/k61r.f>: 

```fortran
      FUNCTION K61R(ISPICK,ITURN,K,L,R, JA)
C BY DANNY C. CHAMPION
C TYPED BY JM 3/27/79
      k61r=ja    ! Added 7/27/93 to report own old value
      IF (ITURN .EQ. 1) K61R = 0
      IF (ISPICK .EQ. 0) ICOOP = ICOOP + 1
      IF (ITURN .LE. 10) RETURN
      K61R = ISPICK
      IF (ITURN .LE. 25) RETURN
      K61R = 0
      COPRAT = FLOAT(ICOOP) / FLOAT(ITURN)
      IF (ISPICK .EQ. 1 .AND. COPRAT .LT. .6 .AND. R .GT. COPRAT)
     +K61R = 1
      RETURN
      END
```

According the description for the Python version <http://axelrod.readthedocs.io/en/stable/reference/all_strategies.html#axelrod.strategies.axelrod_second.Champion>, that looks correct to me.

Here is the transitive fingerprint for the Python version:

```python
>>> import axelrod as axl
>>> axl.TransitiveFingerprint(axl.Champion(), number_of_opponents=20)
>>> data = fp.fingerprint(turns=200)
>>> fp.plot()
```

![download 44](https://user-images.githubusercontent.com/2131546/30590584-21bb51e6-9d37-11e7-9648-c001ab11767e.png)

We see that as expected, the strategy cooperates for 10 turns, plays tft for the next 15 and then "does other stuff": a mix of cooperating and defecting.

Here is the transitive fingerprint for the fortran version:

```python
>>> import axelrod_fortran as axlf
>>> fp = axl.TransitiveFingerprint(axlf.Player("k61r"), number_of_opponents=20)
>>> data = fp.fingerprint(turns=200)
>>> fp.plot();
```

![download 45](https://user-images.githubusercontent.com/2131546/30590895-890d468c-9d38-11e7-9885-35db342cf0dd.png)

We see that the fortran strategy behaves as expected for the first 10 + 15 moves but **just** cooperates thereafter.

Looking at the code it seems to indicate that these lines aren't working as expected:

```fortan
      IF (ISPICK .EQ. 1 .AND. COPRAT .LT. .6 .AND. R .GT. COPRAT)
     +K61R = 1
      RETURN
```

IE `K61R` is never being set to 1. Is that `+` supposed to be there?

FWIW, changing it to:

```fortran
      IF (ISPICK .EQ. 1 .AND. COPRAT .LT. .6 .AND. R .GT. COPRAT) K61R = 1
```

gave me compile error:

```
src/strategies/k61r.f:12:66:

       IF (ISPICK .EQ. 1 .AND. COPRAT .LT. .6 .AND. R .GT. COPRAT) K61R = 1
                                                                  1
Error: Cannot assign to a named constant at (1)
Makefile:52: recipe for target 'obj/strategies/k61r.o' failed
make: *** [obj/strategies/k61r.o] Error 1
```

**Comment by meatballs** [comment]
Looks like another "God is real" issue. ITURN and ISPICK are not declared as integers and so will be treated as reals. As such, they will never be equal to 1 or 0 (they would have to be 1.0 and 0.0 in order to work) and those conditions will always evaluate to false.

**Comment by meatballs** [comment]
I'd suggest re-opening this, creating a branch, adding the declaration, compiling and testing whether the results are different.

**Comment by meatballs** [comment]
> Is that + supposed to be there?

Yes - anything in that column marks the line as a continutation of the previous line. '+' is a common convention, but anything in that column has the same effect.

**Comment by meatballs** [comment]
> Looks like another "God is real" issue. ITURN and ISPICK are not declared as integers and so will be treated as reals. As such, they will never be equal to 1 or 0 (they would have to be 1.0 and 0.0 in order to work) and those conditions will always evaluate to false.

Previously admitted idiocy applies here!

**Comment by meatballs** [comment]
I'd expect to see that condition written as:

`IF ( (ISPICK .EQ. 1) .AND. (COPRAT .LT. .6) .AND. (R .GT. COPRAT) )`

Not sure if it would make any difference or not!

**Comment by drvinceknight** [comment]
I'm investigating :) :+1: (Takes longer to check due to stochastic nature)

**Comment by drvinceknight** [comment]
So as far as I can tell, this strategy is actually working just "fine" (I tried your suggestion and various other things and it made no difference). Not necessarily as intended (and not necessarily as it did in Axelrod's second tournament) but I believe all the Fortran is working correctly, if you look carefully at the fingerprint there is actually a very small number of defections.

```python
>>> axl.seed(0)
>>> match = axl.Match((axlf.Player("k61r"), axl.Random(0.1)), turns=30)
>>> match.play()
[(C, D),
 (C, D),
 (C, D),
 (C, D),
 (C, D),
 (C, D),
 (C, D),
 (C, D),
 (C, D),
 (C, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, C),
 (C, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D)]
```

When you have time (no rush @meatballs), could you merge https://github.com/Axelrod-Python/TourExec/pull/5 and do a new release (or I can do it)? Once that's done I'll rerun the original tournament and then will take another look at any remaining discrepancies.
