### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/axelrod-fortran#87]
@meatballs I've tested the latest updates with a full tournament. For our 2nd tournament revisiting work it would be good to pin a new version number, so when you get a chance, please push a new release.

**Comment by meatballs** [comment]
Will do! 

On August 14, 2020 5:55:52 PM UTC, Marc <notifications@github.com> wrote:
>@meatballs I've tested the latest updates with a full tournament. For
>our 2nd tournament revisiting work it would be good to pin a new
>version number, so when you get a chance, please push a new release.

-- 
Owen Campbell 

This email has been digitally signed. 
For further information visit http://owencampbell.me.uk/pgp
